name: ESP32 Arduino Libs CI

on:
  workflow_dispatch:

jobs:

  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: dist
